# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('record_count', models.IntegerField()),
                ('table', models.CharField(max_length=40)),
            ],
        ),
    ]
