# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-26 11:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0002_dayrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayrecord',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='dayrecord',
            name='record_count',
        ),
        migrations.RemoveField(
            model_name='dayrecord',
            name='table',
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
