# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-26 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0003_auto_20160726_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayrecord',
            old_name='data',
            new_name='records',
        ),
    ]
