# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-27 13:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0004_auto_20160726_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='dayrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dayrecord',
            name='records',
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='row',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
    ]
