# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-27 16:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0005_auto_20160727_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrecord',
            name='row',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
