# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 20:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0011_auto_20160912_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrecord',
            name='row',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=18), null=True, size=None),
        ),
    ]
