# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0014_auto_20160913_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrecord',
            name='row',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None),
        ),
    ]
