# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtable', '0015_auto_20160914_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrecord',
            name='row',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
